[package]
name = "configurable-test-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.28"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "parking_lot", "net", "sync", "time", "macros"] }
